version: "3.7"

services:
  database:
    image: postgres:16.0
    container_name: database_mytraining
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=mytraining
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local