version: "3.7"

services:
  database:
    image: postgres:16.0
    container_name: database_mytraining
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=mytraining
    volumes:
      - pgdata:/data/postgres

  database-test:
    image: postgres:16.0
    container_name: database_mytraining_test
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=mytraining_test
    volumes:
      - pgdata-test:/data/postgres

volumes:
  pgdata:
    driver: local
  pgdata-test:
    driver: local